### ISSUE TITLE
Only accepting standalone projects

### ISSUE THREAD

**Issue by amrrbakry** [mfouad/awesome-egypt-opensource#8]
@mfouad could you please elaborate on the reasoning behind only accepting standalone projects and not accepting API wrappers or SDKs? 

I don't think that these projects (API wrappers - SDKs) necessarily have less value than their standalone counterparts. Also, the reasons mentioned in the [why section in the README](https://github.com/mfouad/awesome-egypt-opensource#why) are pretty much valid for these projects as well.

I opened this issue to start a discussion.

**Comment by mfouad** [comment]
@amrrbakry thank you for starting this discussion. IMO a standalone project is:

- Has a roadmap and multiple features, etc
- Has users and a community
- Has 2+ contributers and needs more.

I also expand on these criteria [here](https://github.com/mfouad/awesome-egypt-opensource/blob/master/CONTRIBUTING.md#criteria-for-accepting-a-new-submitted-project)

Companies like Google or Twilio release REST API and publish an SDK or API Wrapper for their api, the core product itself is closed, APIs are restricted to a usecase, and the SDK is just a punch of "HTTP Requests". 
This project by itself:
- Has no value on its own, it must use the closed source, cloud hosted API to work!
- Requires no contribution from a community, because only the API hosting company know their roadmap and write the APIs for it.
- Cannot be forked or has no point to be forked.
- Is just open source because languages like Ruby, Node.js and Python cannot be closed source or compiled reliablily.
- the barier to entry is very low, if any company that has an API gets to claim to support open source!
- A company will never allow external maintainer or give away their project.

The only SDK or API wrapper that could qualify as a TRUE standalone project is something like [Fog](https://fog.io/), which is a wrapper on many API backends and are not tied to a specific platform

For example I would consider [Resala](https://github.com/RobustaStudio/Resala) a project but Twilio SDK is just an API Wrapper.

**Comment by mfouad** [comment]
After thinking about it, I did not consider individuals will create API wrappers. I think if it is not a project by a company then it should qualify fine.

Most companies publish their own SDKs. but many companies in Egypt don't, so this should qualify as a REALLY helpful project for people trying to use these APIs to save huge amount of time!

**Comment by amrrbakry** [comment]
Hi @mfouad, 

thanks for taking the time to address this. I now understand the criteria better, and it makes total sense. I agree that company-owned API wrappers and SDKs would not be a good fit here because they wouldn't probably accept contributions from the community, and they'd move the project according to their roadmap.

I created the _fawry_ project for the reason you mentioned in the second comment and also for these particular reasons:

- there was no official package for fawry to use with ruby/rails projects
- I wanted to save people the trouble of interacting with fawry's API and its pitfalls (the API is really shitty)
- I wanted to abstract the fawry payment logic from my code

Also, other developers reached out to me asking to port the project to other languages, and that's why I created the fawry-api organization; now the project is ported to nodejs and go. But I think I should write that we're not affiliated with Fawry 😅 (I will add it to the README)

**Comment by mfouad** [comment]
Kudos on the effort, I think the level of documentation and organization in the project led me to think it was company owned!

I think the popular convention is to add (**Unofficial** COMPANY_NAME API wrapper) in the project description or headline will do it.

**Comment by amrrbakry** [comment]
Thank you so much, @mfouad 👍
